version: "2"
services:
  kamailio:
    #build: ./kamailio
    image: wtelecom/kamailio:uc-1
    depends_on:
      - db
      - rtpproxy
      - asterisk
      - mcu
      - mediamixer
    environment:
      - constraint:node==master
      - PUBLICIP=10.200.3.116
    volumes:
      - /home/tech/uc/kamailio:/etc/kamailio
    ports:
      - "5060:5060/udp"
      - "5061:5061/udp"
    hostname: kamailio-h
    extra_hosts:
      - "public_ip:10.200.3.116"
    container_name: kamailio-c
    networks:
      uc-net:
        aliases:
          - kamailio-int

  rtpproxy:
    build: ./rtpproxy
    #image: wtelecom/rtpproxy:uc-1
    depends_on:
      - db
    environment:
      - PUBLIC_IP=
      - PORT_MAX=10399
      - PORT_MIN=10000
      - TIMEOUT=1000
      - SUBNET_OVERLAY=192.168.0.0
      - SUFFIX_OVERLAY=int
      - SUFFIX_GWBRIDGE=ext
      - PORT_RTPPROXY=7711
      - DB_KAMAILIO=kamailio_db
      - DB_USER=kamailio_user
      - DB_PWD=kamailiopwd
      - DB_HOST=db
    ports:
      - "10000-10399:10000-10399/udp"
    expose:
      - "7711"
    hostname: rtpproxy-h
    container_name: rtpproxy
    extra_hosts:
      - "public_ip:10.200.3.116"
    networks:
      uc-net:
        aliases:
          - rtpproxy-int

  db:
    build: ./mysql
    #image: wtelecom/mysql:uc-1
    environment:
      - constraint:node==master
      - MYSQL_ROOT_PASSWORD=supersecret
    volumes:
      - /home/tech/uc/mysql/dataDir:/var/lib/mysql
    hostname: db
    container_name: db
    networks:
      uc-net:
        aliases:
          - db

  asterisk:
    #build: ./asterisk
    image: wtelecom/asterisk:uc-1
    environment:
      - constraint:node==master
    volumes:
      - /home/tech/uc/asterisk:/etc/asterisk
    hostname: asterisk
    networks:
      - uc-net

  mcu:
    #build: ./mcu
    image: wtelecom/medooze-mcu:uc-1
    depends_on:
      - mediamixer
    environment:
      - constraint:node==slave
    ports:
      - "4848:4848"
      - "8080:8080"
      - "8181:8181"
    hostname: mcu
    container_name: mcu
    networks:
      uc-net:
        aliases:
          - mcu-int
        
  mediamixer:
    #build: ./mediamixer
    image: wtelecom/medooze-mediamixer:uc-1
    environment:
      - constraint:node==slave
    # volumes:
    #   - /home/tech/uc/mediamixer:/usr/local/src/medooze/mcu
    hostname: mediamixer
    networks:
      - uc-net    

networks:
  uc-net:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          ip_range: 192.168.0.0/24
          gateway: 192.168.0.1
