version: "2"
services:
  webs:
    image: nginx
    environment:
      - constraint:node==p8-k
    # ports:
    #   - "7000:80"
    hostname: webh
    container_name: webc
    networks:
      uc-net:
        aliases:
          # - webn
          - webc
      # uc-net2:
      #   aliases:
      #     # - webn
      #     - webc
      uc-ext:
        aliases:
          - webe

networks:
  uc-net:
    external:
      name: uc-net
  uc-ext:
    external:
      name: p8-k/uc-ext

# networks:
#   uc-net2:
#     driver: overlay
#     ipam:
#       driver: default
#       config:
#         - subnet: 192.168.69.0/24
#           ip_range: 192.168.69.0/24
#           gateway: 192.168.69.1