version: "2"
services:
  webs:
    image: nginx
    environment:
      - constraint:node==p8-r
    container_name: webc
    hostname: webh
    networks:
      prueba-overlay:
        aliases:
          - web-int

networks:
  prueba-overlay:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 192.168.69.0/24
          ip_range: 192.168.69.0/24
          gateway: 192.168.69.1